# Generated by Django 4.0.3 on 2022-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='user_id')),
                ('fisrt_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('phone_number', models.TextField(default='', max_length=11)),
                ('address', models.TextField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('username', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dateofbirth', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
