# Generated by Django 4.0.3 on 2022-05-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_superadmins_admin_alter_admins_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('podcast_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='podcast_id')),
                ('title', models.TextField(max_length=100)),
                ('content_creator_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('podcast_url', models.URLField(max_length=300)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='video_id')),
                ('title', models.TextField(max_length=100)),
                ('content_creator_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('video_url', models.URLField(max_length=300)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentCreators',
            fields=[
                ('creators_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='creators_id')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('podcast_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_content', to='admin.podcasts')),
                ('video_coontent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_coontent', to='admin.videos')),
            ],
        ),
        migrations.AddField(
            model_name='admins',
            name='content_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contentcreators', to='admin.contentcreators'),
        ),
        migrations.AddField(
            model_name='admins',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='admin.podcasts'),
        ),
        migrations.AddField(
            model_name='admins',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='admin.videos'),
        ),
    ]
