# Generated by Django 4.0.3 on 2022-05-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_podcasts_videos_contentcreators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcreators',
            old_name='video_coontent',
            new_name='video_content',
        ),
    ]
