# Generated by Django 4.0.4 on 2022-05-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_rename_video_coontent_contentcreators_video_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='content_creator',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='video',
        ),
        migrations.RemoveField(
            model_name='contentcreators',
            name='podcast_content',
        ),
        migrations.RemoveField(
            model_name='contentcreators',
            name='video_content',
        ),
        migrations.RemoveField(
            model_name='superadmins',
            name='admin',
        ),
        migrations.AddField(
            model_name='admins',
            name='super_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='admin.superadmins'),
        ),
        migrations.AddField(
            model_name='contentcreators',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_content', to='admin.admins'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_content', to='admin.admins'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='content_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_coontent', to='admin.contentcreators'),
        ),
        migrations.AddField(
            model_name='videos',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='admin.admins'),
        ),
        migrations.AddField(
            model_name='videos',
            name='content_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_coontent', to='admin.contentcreators'),
        ),
    ]
