# Generated by Django 4.0.3 on 2022-05-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
