# Generated by Django 4.0.3 on 2022-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phonenumber',
            field=models.TextField(default='', max_length=11),
        ),
    ]
