# Generated by Django 4.0.3 on 2022-05-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_users_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
