# Generated by Django 4.0.3 on 2022-05-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.TextField(max_length=500),
        ),
    ]
